# In kubernetes/base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels: {app: my-web-app}
  template:
    metadata:
      labels: {app: my-web-app}
    spec:
      containers:
      - name: web-server-container
        # The image tag will be set by the Jenkins pipeline
        image: ghcr.io/riteshn96/multi-cloud-devops-pipeline:latest
        ports:
        - containerPort: 80
        # The env block that was here should be REMOVED from the base file.