# kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
        - name: web-server-container
          # This is the path to your image in GHCR.
          # We will make this dynamic later in Jenkins.
          image: ghcr.io/riteshn96/multi-cloud-devops-pipeline:latest
          ports:
            - containerPort: 80
          env:
            - name: CLOUD_PROVIDER
              value: "AWS"