# kubernetes/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: ghcr.io/riteshn96/multi-cloud-devops-pipeline
  newName: ghcr.io/riteshn96/multi-cloud-devops-pipeline
  newTag: latest